apiVersion: v1
kind: Service
metadata:
  name: techtrends-service
  namespace: {{.Values.namespace.name}}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: techtrends
  ports:
    - protocol: TCP
      port: 4111
      targetPort: 3111