namespace:
  name: sandbox
image:
  repository: alexpereiramaranhao/techtrends
  tag: latest
  pullPolicy: IfNotPresent  
replicasCount: 1
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
replicaCount: 1
resources:
  requests: 
    memory: 64Mi
    CPU: 250m
  limits:
    memory: 128Mi
    CPU: 500m  
containerPort: 3111
livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz  
